package com.poc.cib7.owner;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.annotation.Order;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.web.SecurityFilterChain;

import static org.springframework.security.web.util.matcher.AntPathRequestMatcher.antMatcher;

/**
 * Spring Security filter chain for the public, unauthenticated
 * {@code /api/public/**} surface used by the owner-confirmation flow.
 *
 * <p>Tokens in the {@code /confirm-owner/{token}} URLs ARE the secret —
 * each is a UUID generated by the applicant's form and bound to a single
 * waiting message receive task inside the multi-instance subprocess.
 * Knowledge of the token authorizes the owner to approve or reject.
 *
 * <p>Ordered at {@code 0} so it runs before
 * {@link com.poc.cib7.keycloak.RestApiSecurityConfig} (order 1, matches
 * {@code /engine-rest/**}) and
 * {@link com.poc.cib7.keycloak.webapp.WebappSecurityConfig} (order 2,
 * matches {@code /camunda/**}). The security matcher pins this chain to
 * {@code /api/public/**} so it doesn't shadow the other two.
 */
@Configuration
public class PublicApiSecurityConfig {

    @Bean
    @Order(0)
    public SecurityFilterChain publicApiSecurity(HttpSecurity http) throws Exception {
        return http
                .securityMatcher(antMatcher("/api/public/**"))
                .csrf(csrf -> csrf.ignoringRequestMatchers(antMatcher("/api/public/**")))
                .authorizeHttpRequests(authorize -> authorize.anyRequest().permitAll())
                .build();
    }
}
