package com.poc.backend.registry;

import javax.sql.DataSource;
import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.output.MigrateResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.InitializingBean;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

/**
 * Migrates the service pack's registry tables, separately from the backend's own schema.
 *
 * <p>The pack's migrations ({@code db/registry/V*__*.sql}, generated by the service builder from
 * {@code data/*.md}) run in their own {@code registry} schema with their own Flyway history table.
 * The backend's core tables keep Spring Boot's Flyway in the default schema. So a core release and
 * a pack change never compete for the same version number, and a pack cannot touch a core table.
 */
@Component
public class RegistryMigrations implements InitializingBean {

  private static final Logger LOG = LoggerFactory.getLogger(RegistryMigrations.class);

  private final DataSource dataSource;
  private final String schema;
  private final String[] locations;

  public RegistryMigrations(
      DataSource dataSource,
      @Value("${app.registry.schema:registry}") String schema,
      @Value("${app.registry.migrations:classpath:db/registry}") String[] locations) {
    if (!schema.matches("[a-z][a-z0-9_]{0,62}")) {
      throw new IllegalStateException("app.registry.schema '" + schema + "' is not a plain name");
    }
    this.dataSource = dataSource;
    this.schema = schema;
    this.locations = locations;
  }

  /** The schema the registry tables live in. */
  public String schema() {
    return schema;
  }

  @Override
  public void afterPropertiesSet() {
    MigrateResult result =
        Flyway.configure()
            .dataSource(dataSource)
            .schemas(schema)
            .locations(locations)
            .load()
            .migrate();
    LOG.info(
        "Registry schema '{}' at version {} ({} migration(s) applied)",
        schema,
        result.targetSchemaVersion,
        result.migrationsExecuted);
  }
}
