import { useState, type FormEvent } from 'react';
import type { FormProps } from '../types';

/**
 * Applicant form for ropLearningPermit (PartA) — ROP ITS Demo Scenario 2.
 * Flat 6 OMR service fee shown before any field is filled (demo
 * requirement: cost visible at the beginning). The eye test is NOT a form
 * field — it is fetched from the approved-opticians registry by civil
 * number after submission.
 *
 * Generated by .claude/skills/service-builder from
 * docs/business/services/rop-learning-permit/forms/rop-permit-application.md
 */

const RESIDENCY_OPTIONS = [
  { value: 'citizen', label: 'Omani citizen' },
  { value: 'gcc-citizen', label: 'GCC-country citizen' },
  { value: 'resident', label: 'Resident' },
];

const LICENSE_CATEGORIES = [
  { value: 'light-vehicle', label: 'Light vehicle' },
  { value: 'motorcycle', label: 'Motorcycle' },
  { value: 'heavy-vehicle', label: 'Heavy vehicle' },
  { value: 'mechanical-equipment', label: 'Mechanical equipment' },
];

export default function RopPermitApplicationForm({
  data,
  onComplete,
  submitting,
  readOnly,
}: FormProps) {
  const [applicantName, setApplicantName] = useState((data.applicantName as string) ?? '');
  const [applicantEmail, setApplicantEmail] = useState((data.applicantEmail as string) ?? '');
  const [civilId, setCivilId] = useState((data.civilId as string) ?? '');
  const [age, setAge] = useState(data.age != null ? String(data.age) : '');
  const [residencyStatus, setResidencyStatus] = useState(
    (data.residencyStatus as string) ?? 'citizen',
  );
  const [hasResidentCard, setHasResidentCard] = useState(Boolean(data.hasResidentCard));
  const [licenseCategory, setLicenseCategory] = useState(
    (data.licenseCategory as string) ?? 'light-vehicle',
  );
  const [specialNeeds, setSpecialNeeds] = useState(Boolean(data.specialNeeds));
  const [profession, setProfession] = useState((data.profession as string) ?? '');

  const [error, setError] = useState<string | null>(null);

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError(null);

    if (!applicantName.trim()) {
      setError('Please enter your full name.');
      return;
    }
    if (!applicantEmail.trim() || !applicantEmail.includes('@')) {
      setError('Please enter a valid email address — all notifications go there.');
      return;
    }
    if (!/^[0-9]{8}$/.test(civilId.trim())) {
      setError('The civil number must be exactly 8 digits.');
      return;
    }
    const ageNumber = Number(age);
    if (!Number.isInteger(ageNumber) || ageNumber < 15 || ageNumber > 100) {
      setError('Please enter your age as a whole number between 15 and 100.');
      return;
    }

    await onComplete({
      applicantName: { value: applicantName.trim(), type: 'String' },
      applicantEmail: { value: applicantEmail.trim(), type: 'String' },
      civilId: { value: civilId.trim(), type: 'String' },
      age: { value: ageNumber, type: 'Integer' },
      residencyStatus: { value: residencyStatus, type: 'String' },
      hasResidentCard: { value: hasResidentCard, type: 'Boolean' },
      licenseCategory: { value: licenseCategory, type: 'String' },
      specialNeeds: { value: specialNeeds, type: 'Boolean' },
      profession: { value: profession.trim(), type: 'String' },
    });
  }

  return (
    <form className="form" onSubmit={handleSubmit}>
      <p className="form-intro">
        {readOnly
          ? 'A read-only view of the submitted learning permit application.'
          : 'Apply for a driving learning license from the General Traffic Department (Royal Oman Police).'}
      </p>

      <div className="form-banner">
        <strong>Service fee: 6 OMR</strong>
        <p className="form-banner-body">
          Flat fee for issuing a driving learning license — payable after your application is
          approved.
        </p>
      </div>

      <label className="field">
        <span className="field-label">Full name</span>
        <input
          className="field-input"
          value={applicantName}
          onChange={(e) => setApplicantName(e.target.value)}
          disabled={readOnly}
        />
      </label>

      <label className="field">
        <span className="field-label">Email address</span>
        <input
          className="field-input"
          type="email"
          value={applicantEmail}
          onChange={(e) => setApplicantEmail(e.target.value)}
          disabled={readOnly}
        />
      </label>

      <label className="field">
        <span className="field-label">Civil number</span>
        <input
          className="field-input"
          value={civilId}
          onChange={(e) => setCivilId(e.target.value)}
          placeholder="8 digits"
          disabled={readOnly}
        />
        <span className="field-hint muted">
          Demo civil IDs: 90000001 weak vision (Police Hospital branch), 90000002 failed eye test,
          90000003 no eye test on file, 90000004 already holds a valid license, 90000005
          outstanding restrictions. Any other 8-digit number is all-clear.
        </span>
      </label>

      <label className="field">
        <span className="field-label">Age (years)</span>
        <input
          className="field-input"
          type="number"
          min={15}
          max={100}
          value={age}
          onChange={(e) => setAge(e.target.value)}
          disabled={readOnly}
        />
      </label>

      <label className="field">
        <span className="field-label">Residency status</span>
        <select
          className="field-input"
          value={residencyStatus}
          onChange={(e) => setResidencyStatus(e.target.value)}
          disabled={readOnly}
        >
          {RESIDENCY_OPTIONS.map((o) => (
            <option key={o.value} value={o.value}>
              {o.label}
            </option>
          ))}
        </select>
      </label>

      <label className="field field-checkbox">
        <input
          type="checkbox"
          checked={hasResidentCard}
          onChange={(e) => setHasResidentCard(e.target.checked)}
          disabled={readOnly}
        />
        <span className="field-label">I hold a valid resident card</span>
        <span className="field-hint muted">Required for GCC-country citizens.</span>
      </label>

      <label className="field">
        <span className="field-label">License category</span>
        <select
          className="field-input"
          value={licenseCategory}
          onChange={(e) => setLicenseCategory(e.target.value)}
          disabled={readOnly}
        >
          {LICENSE_CATEGORIES.map((o) => (
            <option key={o.value} value={o.value}>
              {o.label}
            </option>
          ))}
        </select>
        <span className="field-hint muted">
          Heavy vehicle and mechanical equipment require age 21+.
        </span>
      </label>

      <label className="field field-checkbox">
        <input
          type="checkbox"
          checked={specialNeeds}
          onChange={(e) => setSpecialNeeds(e.target.checked)}
          disabled={readOnly}
        />
        <span className="field-label">I am a person with special needs</span>
      </label>

      <label className="field">
        <span className="field-label">Profession (residents)</span>
        <input
          className="field-input"
          value={profession}
          onChange={(e) => setProfession(e.target.value)}
          disabled={readOnly}
        />
        <span className="field-hint muted">
          For residents, the license category must match the profession registered with the
          Ministry of Labor.
        </span>
      </label>

      {error && <p className="form-error">{error}</p>}

      {!readOnly && (
        <div className="form-actions">
          <button type="submit" className="btn btn-primary" disabled={submitting}>
            {submitting ? 'Submitting…' : 'Submit application'}
          </button>
        </div>
      )}
    </form>
  );
}
