import { useState, type FormEvent } from 'react';
import { useTranslation } from 'react-i18next';
import type { FormProps } from '../types';
import { formatCurrency } from '../../i18n/format';

/**
 * Applicant form for ropLearningPermit (PartA) — ROP ITS Demo Scenario 2.
 * Flat 6 OMR service fee shown before any field is filled (demo
 * requirement: cost visible at the beginning). The eye test is NOT a form
 * field — it is fetched from the approved-opticians registry by civil
 * number after submission.
 *
 * Generated by .claude/skills/service-builder from
 * docs/business/services/rop-learning-permit/forms/rop-permit-application.md
 */

const RESIDENCY_OPTIONS = [
  { value: 'citizen', labelKey: 'fields.residencyStatus.options.citizen' },
  { value: 'gcc-citizen', labelKey: 'fields.residencyStatus.options.gccCitizen' },
  { value: 'resident', labelKey: 'fields.residencyStatus.options.resident' },
];

const LICENSE_CATEGORIES = [
  { value: 'light-vehicle', labelKey: 'fields.licenseCategory.options.lightVehicle' },
  { value: 'motorcycle', labelKey: 'fields.licenseCategory.options.motorcycle' },
  { value: 'heavy-vehicle', labelKey: 'fields.licenseCategory.options.heavyVehicle' },
  { value: 'mechanical-equipment', labelKey: 'fields.licenseCategory.options.mechanicalEquipment' },
];

export default function RopPermitApplicationForm({
  data,
  onComplete,
  submitting,
  readOnly,
}: FormProps) {
  const { t } = useTranslation('rop-permit-application');
  const [applicantName, setApplicantName] = useState((data.applicantName as string) ?? '');
  const [applicantEmail, setApplicantEmail] = useState((data.applicantEmail as string) ?? '');
  const [civilId, setCivilId] = useState((data.civilId as string) ?? '');
  const [age, setAge] = useState(data.age != null ? String(data.age) : '');
  const [residencyStatus, setResidencyStatus] = useState(
    (data.residencyStatus as string) ?? 'citizen',
  );
  const [hasResidentCard, setHasResidentCard] = useState(Boolean(data.hasResidentCard));
  const [licenseCategory, setLicenseCategory] = useState(
    (data.licenseCategory as string) ?? 'light-vehicle',
  );
  const [specialNeeds, setSpecialNeeds] = useState(Boolean(data.specialNeeds));
  const [profession, setProfession] = useState((data.profession as string) ?? '');

  /** i18n key of the current validation error, translated at render time. */
  const [error, setError] = useState<string | null>(null);

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError(null);

    if (!applicantName.trim()) {
      setError('errors.nameRequired');
      return;
    }
    if (!applicantEmail.trim() || !applicantEmail.includes('@')) {
      setError('errors.emailInvalid');
      return;
    }
    if (!/^[0-9]{8}$/.test(civilId.trim())) {
      setError('errors.civilIdFormat');
      return;
    }
    const ageNumber = Number(age);
    if (!Number.isInteger(ageNumber) || ageNumber < 15 || ageNumber > 100) {
      setError('errors.ageRange');
      return;
    }

    await onComplete({
      applicantName: { value: applicantName.trim(), type: 'String' },
      applicantEmail: { value: applicantEmail.trim(), type: 'String' },
      civilId: { value: civilId.trim(), type: 'String' },
      age: { value: ageNumber, type: 'Integer' },
      residencyStatus: { value: residencyStatus, type: 'String' },
      hasResidentCard: { value: hasResidentCard, type: 'Boolean' },
      licenseCategory: { value: licenseCategory, type: 'String' },
      specialNeeds: { value: specialNeeds, type: 'Boolean' },
      profession: { value: profession.trim(), type: 'String' },
    });
  }

  return (
    <form className="form" onSubmit={handleSubmit}>
      <p className="form-intro">{readOnly ? t('intro.readOnly') : t('intro.edit')}</p>

      <div className="form-banner">
        <strong>{t('fee.title', { fee: formatCurrency(6, 'OMR') })}</strong>
        <p className="form-banner-body">{t('fee.body')}</p>
      </div>

      <label className="field">
        <span className="field-label">{t('fields.applicantName.label')}</span>
        <input
          className="field-input"
          value={applicantName}
          onChange={(e) => setApplicantName(e.target.value)}
          disabled={readOnly}
        />
      </label>

      <label className="field">
        <span className="field-label">{t('fields.applicantEmail.label')}</span>
        <input
          className="field-input"
          type="email"
          value={applicantEmail}
          onChange={(e) => setApplicantEmail(e.target.value)}
          disabled={readOnly}
        />
      </label>

      <label className="field">
        <span className="field-label">{t('fields.civilId.label')}</span>
        <input
          className="field-input"
          value={civilId}
          onChange={(e) => setCivilId(e.target.value)}
          placeholder={t('fields.civilId.placeholder')}
          disabled={readOnly}
        />
        <span className="field-hint muted">{t('fields.civilId.hint')}</span>
      </label>

      <label className="field">
        <span className="field-label">{t('fields.age.label')}</span>
        <input
          className="field-input"
          type="number"
          min={15}
          max={100}
          value={age}
          onChange={(e) => setAge(e.target.value)}
          disabled={readOnly}
        />
      </label>

      <label className="field">
        <span className="field-label">{t('fields.residencyStatus.label')}</span>
        <select
          className="field-input"
          value={residencyStatus}
          onChange={(e) => setResidencyStatus(e.target.value)}
          disabled={readOnly}
        >
          {RESIDENCY_OPTIONS.map((o) => (
            <option key={o.value} value={o.value}>
              {t(o.labelKey)}
            </option>
          ))}
        </select>
      </label>

      <label className="field field-checkbox">
        <input
          type="checkbox"
          checked={hasResidentCard}
          onChange={(e) => setHasResidentCard(e.target.checked)}
          disabled={readOnly}
        />
        <span className="field-label">{t('fields.hasResidentCard.label')}</span>
        <span className="field-hint muted">{t('fields.hasResidentCard.hint')}</span>
      </label>

      <label className="field">
        <span className="field-label">{t('fields.licenseCategory.label')}</span>
        <select
          className="field-input"
          value={licenseCategory}
          onChange={(e) => setLicenseCategory(e.target.value)}
          disabled={readOnly}
        >
          {LICENSE_CATEGORIES.map((o) => (
            <option key={o.value} value={o.value}>
              {t(o.labelKey)}
            </option>
          ))}
        </select>
        <span className="field-hint muted">{t('fields.licenseCategory.hint')}</span>
      </label>

      <label className="field field-checkbox">
        <input
          type="checkbox"
          checked={specialNeeds}
          onChange={(e) => setSpecialNeeds(e.target.checked)}
          disabled={readOnly}
        />
        <span className="field-label">{t('fields.specialNeeds.label')}</span>
      </label>

      <label className="field">
        <span className="field-label">{t('fields.profession.label')}</span>
        <input
          className="field-input"
          value={profession}
          onChange={(e) => setProfession(e.target.value)}
          disabled={readOnly}
        />
        <span className="field-hint muted">{t('fields.profession.hint')}</span>
      </label>

      {error && <p className="form-error">{t(error)}</p>}

      {!readOnly && (
        <div className="form-actions">
          <button type="submit" className="btn btn-primary" disabled={submitting}>
            {submitting ? t('common:feedback.submitting') : t('actions.submitApplication')}
          </button>
        </div>
      )}
    </form>
  );
}
