import { useEffect, useState } from 'react';
import {
  listAttachments,
  getDownloadUrl,
  categoryLabel,
  DocumentsApiError,
  type DocumentEntry,
} from '../api/documentsApi';

interface Props {
  processInstanceId: string;
  /**
   * Bump to force a refetch (e.g. after the parent completes a task that
   * may have produced new attachments). Optional — falls back to a single
   * fetch on mount.
   */
  refreshKey?: number | string;
}

/**
 * Renders the Documents card shown on both the applicant detail view
 * (ProcessHistoryView) and the civil-servant worklist
 * (TaskDetailView + ReviewApplicationForm).
 *
 * Two visual subsections:
 *   - "Submitted by applicant"  — uploads (today: ID document)
 *   - "Generated by system"     — engine-produced PDFs (approval, certificate)
 *
 * Downloads route through `/api/documents/attachments/{id}/download-url`
 * which mints a 60-second presigned GET URL.
 */
export default function DocumentsCard({ processInstanceId, refreshKey }: Props) {
  const [docs, setDocs] = useState<DocumentEntry[] | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    setError(null);
    listAttachments(processInstanceId)
      .then((d) => {
        if (!cancelled) setDocs(d);
      })
      .catch((e) => {
        if (cancelled) return;
        const msg = e instanceof DocumentsApiError ? e.message : String(e);
        setError(msg);
        setDocs([]);
      });
    return () => {
      cancelled = true;
    };
  }, [processInstanceId, refreshKey]);

  async function handleDownload(attachmentId: string) {
    try {
      const d = await getDownloadUrl(attachmentId);
      window.open(d.url, '_blank', 'noopener,noreferrer');
    } catch (e) {
      const msg = e instanceof DocumentsApiError ? e.message : String(e);
      setError(msg);
    }
  }

  const submitted = (docs ?? []).filter((d) => d.category === 'applicant-id-document');
  const generated = (docs ?? []).filter(
    (d) => d.category === 'generated-approval-pdf' || d.category === 'generated-certificate',
  );

  return (
    <div className="card documents-card">
      <div className="card-head">
        <h2 className="card-title">Documents</h2>
      </div>
      {error && <p className="form-error">{error}</p>}
      {docs === null && !error && <p className="form-intro">Loading…</p>}
      {docs !== null && (
        <>
          <Section title="Submitted by applicant" docs={submitted} onDownload={handleDownload} />
          <Section title="Generated by system" docs={generated} onDownload={handleDownload} />
        </>
      )}
    </div>
  );
}

function Section({
  title,
  docs,
  onDownload,
}: {
  title: string;
  docs: DocumentEntry[];
  onDownload: (id: string) => void;
}) {
  return (
    <section className="documents-card-section">
      <h3 className="documents-card-section-title">{title}</h3>
      {docs.length === 0 ? (
        <p className="documents-card-empty">No documents yet.</p>
      ) : (
        <ul className="document-list">
          {docs.map((d) => (
            <li key={d.id} className="document-row">
              <div className="document-row-meta">
                <span className="document-row-name">{d.filename}</span>
                <span className="document-row-category">{categoryLabel(d.category)}</span>
              </div>
              <button type="button" className="btn btn-link" onClick={() => onDownload(d.id)}>
                Download
              </button>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}
