import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  listAttachments,
  getDownloadUrl,
  categoryLabel,
  DocumentsApiError,
  type DocumentEntry,
} from '../api/documentsApi';

interface Props {
  processInstanceId: string;
  /**
   * Bump to force a refetch (e.g. after the parent completes a task that
   * may have produced new attachments). Optional — falls back to a single
   * fetch on mount.
   */
  refreshKey?: number | string;
}

/**
 * Renders the Documents card shown on both the applicant detail view
 * (ProcessHistoryView) and the civil-servant worklist
 * (TaskDetailView + VehicleReviewForm).
 *
 * Two visual subsections:
 *   - "Submitted by applicant"  — uploads (today: ID document)
 *   - "Generated by system"     — engine-produced PDFs (approval, certificate)
 *
 * Downloads route through `/api/documents/attachments/{id}/download-url`
 * which mints a 60-second presigned GET URL.
 */
export default function DocumentsCard({ processInstanceId, refreshKey }: Props) {
  const { t } = useTranslation('components');
  const [docs, setDocs] = useState<DocumentEntry[] | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    setError(null);
    listAttachments(processInstanceId)
      .then((d) => {
        if (!cancelled) setDocs(d);
      })
      .catch((e) => {
        if (cancelled) return;
        const msg = e instanceof DocumentsApiError ? e.message : String(e);
        setError(msg);
        setDocs([]);
      });
    return () => {
      cancelled = true;
    };
  }, [processInstanceId, refreshKey]);

  async function handleDownload(attachmentId: string) {
    try {
      const d = await getDownloadUrl(attachmentId);
      window.open(d.url, '_blank', 'noopener,noreferrer');
    } catch (e) {
      const msg = e instanceof DocumentsApiError ? e.message : String(e);
      setError(msg);
    }
  }

  // Generated PDFs are the `generated-*` categories; everything else is an
  // applicant upload. Prefix-based so every process's documents bucket
  // correctly — business registration (founder articles, state-fee invoice,
  // B-card) as well as vehicle registration (approval PDF, certificate) —
  // without re-listing each category here.
  const generated = (docs ?? []).filter((d) => d.category.startsWith('generated-'));
  const submitted = (docs ?? []).filter((d) => !d.category.startsWith('generated-'));

  return (
    <div className="card documents-card">
      <div className="card-head">
        <h2 className="card-title">{t('documents.title')}</h2>
      </div>
      {error && <p className="form-error">{error}</p>}
      {docs === null && !error && <p className="form-intro">{t('common:feedback.loading')}</p>}
      {docs !== null && (
        <>
          <Section
            title={t('documents.submittedByApplicant')}
            docs={submitted}
            onDownload={handleDownload}
          />
          <Section
            title={t('documents.generatedBySystem')}
            docs={generated}
            onDownload={handleDownload}
          />
        </>
      )}
    </div>
  );
}

function Section({
  title,
  docs,
  onDownload,
}: {
  title: string;
  docs: DocumentEntry[];
  onDownload: (id: string) => void;
}) {
  const { t } = useTranslation('components');
  return (
    <section className="documents-card-section">
      <h3 className="documents-card-section-title">{title}</h3>
      {docs.length === 0 ? (
        <p className="documents-card-empty">{t('documents.empty')}</p>
      ) : (
        <ul className="document-list">
          {docs.map((d) => (
            <li key={d.id} className="document-row">
              <div className="document-row-meta">
                <span className="document-row-name">{d.filename}</span>
                <span className="document-row-category">
                  {t(`documents.categories.${d.category}`, {
                    defaultValue: categoryLabel(d.category),
                  })}
                </span>
              </div>
              <button type="button" className="btn btn-link" onClick={() => onDownload(d.id)}>
                {t('common:actions.download')}
              </button>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}
