import { useState } from 'react';
import type { FormProps } from '../types';

/**
 * Traffic officer review form for ropVehicleRegistration (PartB) — ROP
 * ITS Demo Scenario 1: "Approve the request / Reject the request / Return
 * to request an inquiry about the request". The unused reason variable is
 * always completed as an empty string so the shared rejection-email
 * template never sees a stale value.
 *
 * Generated by .claude/skills/service-builder from
 * docs/business/services/rop-vehicle-registration/forms/rop-vehicle-officer-review.md
 */

function check(v: unknown): string {
  if (v === true || v === 'true') return '✓ yes';
  if (v === false || v === 'false') return '✗ no';
  return '—';
}

export default function RopVehicleOfficerReviewForm({
  data,
  onComplete,
  submitting,
  readOnly,
}: FormProps) {
  const [mode, setMode] = useState<'none' | 'sendback' | 'reject'>('none');
  const [reason, setReason] = useState('');
  const [error, setError] = useState<string | null>(null);

  function approve() {
    setError(null);
    return onComplete({
      decision: { value: 'approve', type: 'String' },
      rejectionReason: { value: '', type: 'String' },
      sendBackReason: { value: '', type: 'String' },
    });
  }

  function confirmSendBack() {
    setError(null);
    const trimmed = reason.trim();
    if (!trimmed) {
      setError('Please give the applicant notes on what to correct.');
      return;
    }
    return onComplete({
      decision: { value: 'sendback', type: 'String' },
      sendBackReason: { value: trimmed, type: 'String' },
      rejectionReason: { value: '', type: 'String' },
    });
  }

  function confirmReject() {
    setError(null);
    const trimmed = reason.trim();
    if (!trimmed) {
      setError('Please give the applicant the reason for the rejection.');
      return;
    }
    return onComplete({
      decision: { value: 'reject', type: 'String' },
      rejectionReason: { value: trimmed, type: 'String' },
      sendBackReason: { value: '', type: 'String' },
    });
  }

  const fee =
    data.registrationFee != null && data.registrationFee !== ''
      ? `${Number(String(data.registrationFee).replace(/[^0-9.]/g, '')).toFixed(3)} OMR`
      : '—';
  const decision = (data.decision as string) ?? null;

  return (
    <div className="form">
      <p className="form-intro">
        {readOnly
          ? 'A read-only view of the application and the traffic officer’s decision.'
          : 'Traffic officer review. The system has verified the technical inspection, insurance, and restrictions. Approve to request the fee payment, return for corrections, or reject with a reason.'}
      </p>

      <dl className="summary">
        <div className="summary-row">
          <dt>Owner</dt>
          <dd>{(data.applicantName as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>Email</dt>
          <dd>{(data.applicantEmail as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>Civil number</dt>
          <dd>{(data.civilId as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>Residency status</dt>
          <dd>{(data.residencyStatus as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>Registration type</dt>
          <dd>{(data.registrationType as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>Vehicle category</dt>
          <dd>{(data.vehicleCategory as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>Chassis number (VIN)</dt>
          <dd>{(data.vin as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>Plate request</dt>
          <dd>
            {(data.plateOption as string) === 'reserved'
              ? `Reserved plate ${(data.reservedPlateNumber as string) || '—'}`
              : 'New random plate'}
          </dd>
        </div>
        <div className="summary-row">
          <dt>Technical inspection</dt>
          <dd>{check(data.inspectionPassed)}</dd>
        </div>
        <div className="summary-row">
          <dt>Insurance</dt>
          <dd>{check(data.insured)}</dd>
        </div>
        <div className="summary-row">
          <dt>Restrictions cleared</dt>
          <dd>{check(data.restrictionsCleared)}</dd>
        </div>
        <div className="summary-row">
          <dt>Registration fee</dt>
          <dd>{fee}</dd>
        </div>
        {readOnly && decision && (
          <div className="summary-row">
            <dt>Decision</dt>
            <dd className={decision === 'approve' ? 'decision-approve' : 'decision-reject'}>
              {decision === 'approve'
                ? 'Approved'
                : decision === 'reject'
                  ? 'Rejected'
                  : 'Returned for corrections'}
            </dd>
          </div>
        )}
        {readOnly && Boolean((data.rejectionReason as string) || (data.sendBackReason as string)) && (
          <div className="summary-row">
            <dt>Reason</dt>
            <dd>{(data.rejectionReason as string) || (data.sendBackReason as string)}</dd>
          </div>
        )}
      </dl>

      {!readOnly && mode !== 'none' && (
        <label className="field">
          <span className="field-label">
            {mode === 'sendback' ? 'Notes to the applicant' : 'Rejection reason'}
          </span>
          <textarea
            className="field-input"
            rows={3}
            value={reason}
            onChange={(e) => setReason(e.target.value)}
            placeholder={
              mode === 'sendback'
                ? 'Tell the applicant what to correct (e.g. missing sale letter).'
                : 'Tell the applicant why the application is rejected.'
            }
            autoFocus
          />
        </label>
      )}

      {error && <p className="form-error">{error}</p>}

      {!readOnly && (
        <div className="form-actions">
          {mode === 'none' && (
            <>
              <button className="btn btn-primary" disabled={submitting} onClick={approve}>
                {submitting ? 'Working…' : 'Approve'}
              </button>
              <button
                type="button"
                className="btn"
                disabled={submitting}
                onClick={() => {
                  setMode('sendback');
                  setError(null);
                }}
              >
                Return for corrections…
              </button>
              <button
                type="button"
                className="btn btn-danger"
                disabled={submitting}
                onClick={() => {
                  setMode('reject');
                  setError(null);
                }}
              >
                Reject…
              </button>
            </>
          )}
          {mode !== 'none' && (
            <>
              <button
                className={mode === 'reject' ? 'btn btn-danger' : 'btn btn-primary'}
                disabled={submitting}
                onClick={mode === 'reject' ? confirmReject : confirmSendBack}
              >
                {submitting
                  ? 'Working…'
                  : mode === 'reject'
                    ? 'Confirm rejection'
                    : 'Confirm return'}
              </button>
              <button
                type="button"
                className="btn"
                disabled={submitting}
                onClick={() => {
                  setMode('none');
                  setError(null);
                }}
              >
                Cancel
              </button>
            </>
          )}
        </div>
      )}
    </div>
  );
}
