import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import type { TFunction } from 'i18next';
import { formatCurrency } from '../../i18n/format';
import type { FormProps } from '../types';

/**
 * Traffic officer review form for ropVehicleRegistration (PartB) — ROP
 * ITS Demo Scenario 1: "Approve the request / Reject the request / Return
 * to request an inquiry about the request". The unused reason variable is
 * always completed as an empty string so the shared rejection-email
 * template never sees a stale value.
 *
 * Generated by .claude/skills/service-builder from
 * docs/business/services/rop-vehicle-registration/forms/rop-vehicle-officer-review.md
 */

function check(t: TFunction, v: unknown): string {
  if (v === true || v === 'true') return `✓ ${t('summary.yes')}`;
  if (v === false || v === 'false') return `✗ ${t('summary.no')}`;
  return '—';
}

export default function RopVehicleOfficerReviewForm({
  data,
  onComplete,
  submitting,
  readOnly,
}: FormProps) {
  const { t } = useTranslation('rop-vehicle-officer-review');
  const [mode, setMode] = useState<'none' | 'sendback' | 'reject'>('none');
  const [reason, setReason] = useState('');
  const [error, setError] = useState<string | null>(null);

  function approve() {
    setError(null);
    return onComplete({
      decision: { value: 'approve', type: 'String' },
      rejectionReason: { value: '', type: 'String' },
      sendBackReason: { value: '', type: 'String' },
    });
  }

  function confirmSendBack() {
    setError(null);
    const trimmed = reason.trim();
    if (!trimmed) {
      setError(t('errors.sendBackReasonRequired'));
      return;
    }
    return onComplete({
      decision: { value: 'sendback', type: 'String' },
      sendBackReason: { value: trimmed, type: 'String' },
      rejectionReason: { value: '', type: 'String' },
    });
  }

  function confirmReject() {
    setError(null);
    const trimmed = reason.trim();
    if (!trimmed) {
      setError(t('errors.rejectionReasonRequired'));
      return;
    }
    return onComplete({
      decision: { value: 'reject', type: 'String' },
      rejectionReason: { value: trimmed, type: 'String' },
      sendBackReason: { value: '', type: 'String' },
    });
  }

  const fee =
    data.registrationFee != null && data.registrationFee !== ''
      ? formatCurrency(Number(String(data.registrationFee).replace(/[^0-9.]/g, '')), 'OMR')
      : '—';
  const decision = (data.decision as string) ?? null;

  return (
    <div className="form">
      <p className="form-intro">
        {readOnly ? t('intro.readOnly') : t('intro.edit')}
      </p>

      <dl className="summary">
        <div className="summary-row">
          <dt>{t('summary.owner')}</dt>
          <dd>{(data.applicantName as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>{t('summary.email')}</dt>
          <dd>{(data.applicantEmail as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>{t('summary.civilNumber')}</dt>
          <dd>{(data.civilId as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>{t('summary.residencyStatus')}</dt>
          <dd>{(data.residencyStatus as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>{t('summary.registrationType')}</dt>
          <dd>{(data.registrationType as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>{t('summary.vehicleCategory')}</dt>
          <dd>{(data.vehicleCategory as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>{t('summary.chassisNumber')}</dt>
          <dd>{(data.vin as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>{t('summary.plateRequest')}</dt>
          <dd>
            {(data.plateOption as string) === 'reserved'
              ? t('summary.reservedPlate', { number: (data.reservedPlateNumber as string) || '—' })
              : t('summary.newRandomPlate')}
          </dd>
        </div>
        <div className="summary-row">
          <dt>{t('summary.technicalInspection')}</dt>
          <dd>{check(t, data.inspectionPassed)}</dd>
        </div>
        <div className="summary-row">
          <dt>{t('summary.insurance')}</dt>
          <dd>{check(t, data.insured)}</dd>
        </div>
        <div className="summary-row">
          <dt>{t('summary.restrictionsCleared')}</dt>
          <dd>{check(t, data.restrictionsCleared)}</dd>
        </div>
        <div className="summary-row">
          <dt>{t('summary.registrationFee')}</dt>
          <dd>{fee}</dd>
        </div>
        {readOnly && decision && (
          <div className="summary-row">
            <dt>{t('summary.decision')}</dt>
            <dd className={decision === 'approve' ? 'decision-approve' : 'decision-reject'}>
              {decision === 'approve'
                ? t('common:status.approved')
                : decision === 'reject'
                  ? t('common:status.rejected')
                  : t('decision.returnedForCorrections')}
            </dd>
          </div>
        )}
        {readOnly && Boolean((data.rejectionReason as string) || (data.sendBackReason as string)) && (
          <div className="summary-row">
            <dt>{t('summary.reason')}</dt>
            <dd>{(data.rejectionReason as string) || (data.sendBackReason as string)}</dd>
          </div>
        )}
      </dl>

      {!readOnly && mode !== 'none' && (
        <label className="field">
          <span className="field-label">
            {mode === 'sendback' ? t('fields.reason.labelSendBack') : t('fields.reason.labelReject')}
          </span>
          <textarea
            className="field-input"
            rows={3}
            value={reason}
            onChange={(e) => setReason(e.target.value)}
            placeholder={
              mode === 'sendback'
                ? t('fields.reason.placeholderSendBack')
                : t('fields.reason.placeholderReject')
            }
            autoFocus
          />
        </label>
      )}

      {error && <p className="form-error">{error}</p>}

      {!readOnly && (
        <div className="form-actions">
          {mode === 'none' && (
            <>
              <button className="btn btn-primary" disabled={submitting} onClick={approve}>
                {submitting ? t('common:feedback.submitting') : t('common:actions.approve')}
              </button>
              <button
                type="button"
                className="btn"
                disabled={submitting}
                onClick={() => {
                  setMode('sendback');
                  setError(null);
                }}
              >
                {t('actions.returnForCorrections')}
              </button>
              <button
                type="button"
                className="btn btn-danger"
                disabled={submitting}
                onClick={() => {
                  setMode('reject');
                  setError(null);
                }}
              >
                {t('actions.reject')}
              </button>
            </>
          )}
          {mode !== 'none' && (
            <>
              <button
                className={mode === 'reject' ? 'btn btn-danger' : 'btn btn-primary'}
                disabled={submitting}
                onClick={mode === 'reject' ? confirmReject : confirmSendBack}
              >
                {submitting
                  ? t('common:feedback.submitting')
                  : mode === 'reject'
                    ? t('actions.confirmRejection')
                    : t('actions.confirmReturn')}
              </button>
              <button
                type="button"
                className="btn"
                disabled={submitting}
                onClick={() => {
                  setMode('none');
                  setError(null);
                }}
              >
                {t('common:actions.cancel')}
              </button>
            </>
          )}
        </div>
      )}
    </div>
  );
}
