import type { ComponentType } from 'react';
import type { FormProps } from './types';
import BusinessDetailsForm from './business-details/BusinessDetailsForm';
import OwnerVehicleForm from './owner-vehicle/OwnerVehicleForm';
import ReviewBusinessRegistrationForm from './review-business-registration/ReviewBusinessRegistrationForm';
import VehicleReviewForm from './vehicle-review/VehicleReviewForm';

/**
 * Maps a logical form id to a React component. The form id is the part of the
 * BPMN `camunda:formKey` after the `react:` prefix (spec §6.1, §8.3).
 *
 * Generated by .claude/skills/service-builder — adding a form = add its
 * folder under src/forms/ and re-run /service-builder. Order: alphabetical
 * by form id.
 */
export const formRegistry: Record<string, ComponentType<FormProps>> = {
  'business-details': BusinessDetailsForm,
  'owner-vehicle': OwnerVehicleForm,
  'review-business-registration': ReviewBusinessRegistrationForm,
  'vehicle-review': VehicleReviewForm,
};

/** Parses a BPMN formKey ("react:owner-vehicle") into a form id. */
export function parseFormId(formKey: string | null | undefined): string | null {
  if (!formKey) return null;
  const prefix = 'react:';
  return formKey.startsWith(prefix) ? formKey.slice(prefix.length) : formKey;
}
