import { useState, type FormEvent } from 'react';
import type { FormProps } from '../types';

/**
 * Applicant form for ropVehicleRegistration (PartA) — ROP ITS Demo
 * Scenario 1. The registration fee for the selected category is shown
 * live BEFORE submitting (demo requirement: cost visible at the
 * beginning). The client-side fee table mirrors the rop-vehicle-fee DMN,
 * which stays authoritative for what is actually charged.
 *
 * Generated by .claude/skills/service-builder from
 * docs/business/services/rop-vehicle-registration/forms/rop-vehicle-application.md
 */

const VEHICLE_CATEGORIES: { value: string; label: string; fee: number }[] = [
  { value: 'motorcycle', label: 'Motorcycle', fee: 10 },
  { value: 'private-lt1500', label: 'Private car — engine under 1500 cm³', fee: 15 },
  { value: 'private-1500-3000', label: 'Private car — engine 1500–3000 cm³', fee: 20 },
  { value: 'private-3000-4500', label: 'Private car — engine 3000–4500 cm³', fee: 30 },
  { value: 'private-gt4500', label: 'Private car — engine over 4500 cm³', fee: 50 },
  { value: 'electric-lt75kw', label: 'Electric — motor under 75 kW', fee: 15 },
  { value: 'electric-75-150kw', label: 'Electric — motor 75–150 kW', fee: 20 },
  { value: 'electric-150-224kw', label: 'Electric — motor 150–224 kW', fee: 30 },
  { value: 'electric-gt224kw', label: 'Electric — motor over 224 kW', fee: 50 },
  { value: 'tractor', label: 'Tractor', fee: 40 },
  { value: 'truck-3-5t', label: 'Truck — 3 to 5 tons', fee: 120 },
  { value: 'truck-gte5t', label: 'Truck — 5 tons and above', fee: 180 },
];

const RESIDENCY_OPTIONS = [
  { value: 'citizen', label: 'Omani citizen' },
  { value: 'resident', label: 'Resident' },
  { value: 'diplomat', label: 'Diplomatic mission' },
  { value: 'visitor', label: 'Visitor' },
];

const REGISTRATION_TYPES = [
  { value: 'private', label: 'Private' },
  { value: 'commercial', label: 'Commercial' },
  { value: 'public-utility', label: 'Public utility (taxi / education / crane)' },
  { value: 'diplomatic', label: 'Diplomatic' },
];

export default function RopVehicleApplicationForm({
  data,
  onComplete,
  submitting,
  readOnly,
}: FormProps) {
  const [applicantName, setApplicantName] = useState((data.applicantName as string) ?? '');
  const [applicantEmail, setApplicantEmail] = useState((data.applicantEmail as string) ?? '');
  const [civilId, setCivilId] = useState((data.civilId as string) ?? '');
  const [residencyStatus, setResidencyStatus] = useState(
    (data.residencyStatus as string) ?? 'citizen',
  );
  const [registrationType, setRegistrationType] = useState(
    (data.registrationType as string) ?? 'private',
  );
  const [vehicleCategory, setVehicleCategory] = useState(
    (data.vehicleCategory as string) ?? 'private-lt1500',
  );
  const [vin, setVin] = useState((data.vin as string) ?? '');
  const [plateOption, setPlateOption] = useState((data.plateOption as string) ?? 'random');
  const [reservedPlateNumber, setReservedPlateNumber] = useState(
    (data.reservedPlateNumber as string) ?? '',
  );

  const sendBackReason = (data.sendBackReason as string) ?? '';
  const isResubmission = Boolean(sendBackReason) && !readOnly;

  const [error, setError] = useState<string | null>(null);

  const selectedCategory =
    VEHICLE_CATEGORIES.find((c) => c.value === vehicleCategory) ?? VEHICLE_CATEGORIES[1];

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError(null);

    if (!applicantName.trim()) {
      setError('Please enter the owner’s full name.');
      return;
    }
    if (!applicantEmail.trim() || !applicantEmail.includes('@')) {
      setError('Please enter a valid email address — all notifications go there.');
      return;
    }
    if (!/^[0-9]{8}$/.test(civilId.trim())) {
      setError('The civil number must be exactly 8 digits.');
      return;
    }
    const trimmedVin = vin.trim().toUpperCase();
    if (!/^[A-Z0-9]{11,17}$/.test(trimmedVin)) {
      setError('The chassis number (VIN) must be 11–17 letters/digits.');
      return;
    }
    if (plateOption === 'reserved' && !reservedPlateNumber.trim()) {
      setError('Please enter your reserved plate number (or choose a new random plate).');
      return;
    }

    await onComplete({
      applicantName: { value: applicantName.trim(), type: 'String' },
      applicantEmail: { value: applicantEmail.trim(), type: 'String' },
      civilId: { value: civilId.trim(), type: 'String' },
      residencyStatus: { value: residencyStatus, type: 'String' },
      registrationType: { value: registrationType, type: 'String' },
      vehicleCategory: { value: vehicleCategory, type: 'String' },
      vin: { value: trimmedVin, type: 'String' },
      plateOption: { value: plateOption, type: 'String' },
      reservedPlateNumber: {
        value: plateOption === 'reserved' ? reservedPlateNumber.trim().toUpperCase() : '',
        type: 'String',
      },
      sendBackReason: { value: '', type: 'String' },
    });
  }

  return (
    <form className="form" onSubmit={handleSubmit}>
      {isResubmission && (
        <div className="form-banner form-banner-warn">
          <strong>Returned for corrections.</strong>
          <p className="form-banner-body">{sendBackReason}</p>
        </div>
      )}

      <p className="form-intro">
        {readOnly
          ? 'A read-only view of the submitted vehicle registration application.'
          : isResubmission
            ? 'Your application was returned by the traffic officer. Update the details below and resubmit.'
            : 'Register a new vehicle with the General Traffic Department (Royal Oman Police). The registration fee for your vehicle category is shown below before you submit.'}
      </p>

      <div className="form-banner">
        <strong>Registration fee: {selectedCategory.fee} OMR</strong>
        <p className="form-banner-body">
          Fee for “{selectedCategory.label}” per the General Traffic Department fee schedule.
          Payable after the traffic officer approves the application.
        </p>
      </div>

      <label className="field">
        <span className="field-label">Owner full name</span>
        <input
          className="field-input"
          value={applicantName}
          onChange={(e) => setApplicantName(e.target.value)}
          disabled={readOnly}
        />
      </label>

      <label className="field">
        <span className="field-label">Email address</span>
        <input
          className="field-input"
          type="email"
          value={applicantEmail}
          onChange={(e) => setApplicantEmail(e.target.value)}
          disabled={readOnly}
        />
      </label>

      <label className="field">
        <span className="field-label">Civil number</span>
        <input
          className="field-input"
          value={civilId}
          onChange={(e) => setCivilId(e.target.value)}
          placeholder="8 digits"
          disabled={readOnly}
        />
      </label>

      <label className="field">
        <span className="field-label">Residency status</span>
        <select
          className="field-input"
          value={residencyStatus}
          onChange={(e) => setResidencyStatus(e.target.value)}
          disabled={readOnly}
        >
          {RESIDENCY_OPTIONS.map((o) => (
            <option key={o.value} value={o.value}>
              {o.label}
            </option>
          ))}
        </select>
      </label>

      <label className="field">
        <span className="field-label">Registration type</span>
        <select
          className="field-input"
          value={registrationType}
          onChange={(e) => setRegistrationType(e.target.value)}
          disabled={readOnly}
        >
          {REGISTRATION_TYPES.map((o) => (
            <option key={o.value} value={o.value}>
              {o.label}
            </option>
          ))}
        </select>
      </label>

      <label className="field">
        <span className="field-label">Vehicle category</span>
        <select
          className="field-input"
          value={vehicleCategory}
          onChange={(e) => setVehicleCategory(e.target.value)}
          disabled={readOnly}
        >
          {VEHICLE_CATEGORIES.map((c) => (
            <option key={c.value} value={c.value}>
              {c.label} — {c.fee} OMR
            </option>
          ))}
        </select>
      </label>

      <label className="field">
        <span className="field-label">Chassis number (VIN)</span>
        <input
          className="field-input"
          value={vin}
          onChange={(e) => setVin(e.target.value.toUpperCase())}
          placeholder="11–17 letters/digits"
          disabled={readOnly}
        />
        <span className="field-hint muted">
          Demo VINs: ROPDEMOFAILINSP01 (failed inspection), ROPDEMONOINSURE02 (uninsured),
          ROPDEMOFINESDUE03 (outstanding fines). Any other VIN is all-clear.
        </span>
      </label>

      <label className="field">
        <span className="field-label">Plate number</span>
        <select
          className="field-input"
          value={plateOption}
          onChange={(e) => setPlateOption(e.target.value)}
          disabled={readOnly}
        >
          <option value="random">New random plate</option>
          <option value="reserved">Previously reserved plate</option>
        </select>
      </label>

      {plateOption === 'reserved' && (
        <label className="field">
          <span className="field-label">Reserved plate number</span>
          <input
            className="field-input"
            value={reservedPlateNumber}
            onChange={(e) => setReservedPlateNumber(e.target.value)}
            disabled={readOnly}
          />
        </label>
      )}

      {error && <p className="form-error">{error}</p>}

      {!readOnly && (
        <div className="form-actions">
          <button type="submit" className="btn btn-primary" disabled={submitting}>
            {submitting ? 'Submitting…' : 'Submit application'}
          </button>
        </div>
      )}
    </form>
  );
}
