import { useState, type FormEvent } from 'react';
import { useTranslation } from 'react-i18next';
import { formatCurrency } from '../../i18n/format';
import type { FormProps } from '../types';

/**
 * Applicant form for transportVehicleRegistration (PartA) — ITS Demo
 * Scenario 1. The registration fee for the selected category is shown
 * live BEFORE submitting (demo requirement: cost visible at the
 * beginning). The client-side fee table mirrors the transport-vehicle-fee DMN,
 * which stays authoritative for what is actually charged.
 *
 * Generated by .claude/skills/service-builder from
 * docs/business/services/transport-vehicle-registration/forms/transport-vehicle-application.md
 */

const VEHICLE_CATEGORIES: { value: string; labelKey: string; fee: number }[] = [
  { value: 'motorcycle', labelKey: 'motorcycle', fee: 10 },
  { value: 'private-lt1500', labelKey: 'privateLt1500', fee: 15 },
  { value: 'private-1500-3000', labelKey: 'private1500To3000', fee: 20 },
  { value: 'private-3000-4500', labelKey: 'private3000To4500', fee: 30 },
  { value: 'private-gt4500', labelKey: 'privateGt4500', fee: 50 },
  { value: 'electric-lt75kw', labelKey: 'electricLt75kw', fee: 15 },
  { value: 'electric-75-150kw', labelKey: 'electric75To150kw', fee: 20 },
  { value: 'electric-150-224kw', labelKey: 'electric150To224kw', fee: 30 },
  { value: 'electric-gt224kw', labelKey: 'electricGt224kw', fee: 50 },
  { value: 'tractor', labelKey: 'tractor', fee: 40 },
  { value: 'truck-3-5t', labelKey: 'truck3To5t', fee: 120 },
  { value: 'truck-gte5t', labelKey: 'truckGte5t', fee: 180 },
];

const RESIDENCY_OPTIONS = [
  { value: 'citizen', labelKey: 'citizen' },
  { value: 'resident', labelKey: 'resident' },
  { value: 'diplomat', labelKey: 'diplomat' },
  { value: 'visitor', labelKey: 'visitor' },
];

const REGISTRATION_TYPES = [
  { value: 'private', labelKey: 'private' },
  { value: 'commercial', labelKey: 'commercial' },
  { value: 'public-utility', labelKey: 'publicUtility' },
  { value: 'diplomatic', labelKey: 'diplomatic' },
];

export default function TransportVehicleApplicationForm({
  data,
  onComplete,
  submitting,
  readOnly,
}: FormProps) {
  const { t } = useTranslation('transport-vehicle-application');
  const [applicantName, setApplicantName] = useState((data.applicantName as string) ?? '');
  const [applicantEmail, setApplicantEmail] = useState((data.applicantEmail as string) ?? '');
  const [civilId, setCivilId] = useState((data.civilId as string) ?? '');
  const [residencyStatus, setResidencyStatus] = useState(
    (data.residencyStatus as string) ?? 'citizen',
  );
  const [registrationType, setRegistrationType] = useState(
    (data.registrationType as string) ?? 'private',
  );
  const [vehicleCategory, setVehicleCategory] = useState(
    (data.vehicleCategory as string) ?? 'private-lt1500',
  );
  const [vin, setVin] = useState((data.vin as string) ?? '');
  const [plateOption, setPlateOption] = useState((data.plateOption as string) ?? 'random');
  const [reservedPlateNumber, setReservedPlateNumber] = useState(
    (data.reservedPlateNumber as string) ?? '',
  );

  const sendBackReason = (data.sendBackReason as string) ?? '';
  const isResubmission = Boolean(sendBackReason) && !readOnly;

  const [error, setError] = useState<string | null>(null);

  const selectedCategory =
    VEHICLE_CATEGORIES.find((c) => c.value === vehicleCategory) ?? VEHICLE_CATEGORIES[1];

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError(null);

    if (!applicantName.trim()) {
      setError('errors.ownerName');
      return;
    }
    if (!applicantEmail.trim() || !applicantEmail.includes('@')) {
      setError('errors.email');
      return;
    }
    if (!/^[0-9]{8}$/.test(civilId.trim())) {
      setError('errors.civilId');
      return;
    }
    const trimmedVin = vin.trim().toUpperCase();
    if (!/^[A-Z0-9]{11,17}$/.test(trimmedVin)) {
      setError('errors.vin');
      return;
    }
    if (plateOption === 'reserved' && !reservedPlateNumber.trim()) {
      setError('errors.reservedPlate');
      return;
    }

    await onComplete({
      applicantName: { value: applicantName.trim(), type: 'String' },
      applicantEmail: { value: applicantEmail.trim(), type: 'String' },
      civilId: { value: civilId.trim(), type: 'String' },
      residencyStatus: { value: residencyStatus, type: 'String' },
      registrationType: { value: registrationType, type: 'String' },
      vehicleCategory: { value: vehicleCategory, type: 'String' },
      vin: { value: trimmedVin, type: 'String' },
      plateOption: { value: plateOption, type: 'String' },
      reservedPlateNumber: {
        value: plateOption === 'reserved' ? reservedPlateNumber.trim().toUpperCase() : '',
        type: 'String',
      },
      sendBackReason: { value: '', type: 'String' },
    });
  }

  return (
    <form className="form" onSubmit={handleSubmit}>
      {isResubmission && (
        <div className="form-banner form-banner-warn">
          <strong>{t('banners.returnedForCorrections')}</strong>
          <p className="form-banner-body">{sendBackReason}</p>
        </div>
      )}

      <p className="form-intro">
        {readOnly
          ? t('intro.readOnly')
          : isResubmission
            ? t('intro.resubmission')
            : t('intro.default')}
      </p>

      <div className="form-banner">
        <strong>
          {t('feeBanner.title', { fee: formatCurrency(selectedCategory.fee, 'EUR') })}
        </strong>
        <p className="form-banner-body">
          {t('feeBanner.body', { category: t(`categories.${selectedCategory.labelKey}`) })}
        </p>
      </div>

      <label className="field">
        <span className="field-label">{t('fields.ownerName.label')}</span>
        <input
          className="field-input"
          value={applicantName}
          onChange={(e) => setApplicantName(e.target.value)}
          disabled
        />
        <span className="field-hint muted">{t('common:identity.fromAccount')}</span>
      </label>

      <label className="field">
        <span className="field-label">{t('fields.email.label')}</span>
        <input
          className="field-input"
          type="email"
          value={applicantEmail}
          onChange={(e) => setApplicantEmail(e.target.value)}
          disabled
        />
        <span className="field-hint muted">{t('common:identity.fromAccount')}</span>
      </label>

      <label className="field">
        <span className="field-label">{t('fields.civilId.label')}</span>
        <input
          className="field-input"
          value={civilId}
          onChange={(e) => setCivilId(e.target.value)}
          placeholder={t('fields.civilId.placeholder')}
          disabled={readOnly}
        />
      </label>

      <label className="field">
        <span className="field-label">{t('fields.residencyStatus.label')}</span>
        <select
          className="field-input"
          value={residencyStatus}
          onChange={(e) => setResidencyStatus(e.target.value)}
          disabled={readOnly}
        >
          {RESIDENCY_OPTIONS.map((o) => (
            <option key={o.value} value={o.value}>
              {t(`residency.${o.labelKey}`)}
            </option>
          ))}
        </select>
      </label>

      <label className="field">
        <span className="field-label">{t('fields.registrationType.label')}</span>
        <select
          className="field-input"
          value={registrationType}
          onChange={(e) => setRegistrationType(e.target.value)}
          disabled={readOnly}
        >
          {REGISTRATION_TYPES.map((o) => (
            <option key={o.value} value={o.value}>
              {t(`registrationTypes.${o.labelKey}`)}
            </option>
          ))}
        </select>
      </label>

      <label className="field">
        <span className="field-label">{t('fields.vehicleCategory.label')}</span>
        <select
          className="field-input"
          value={vehicleCategory}
          onChange={(e) => setVehicleCategory(e.target.value)}
          disabled={readOnly}
        >
          {VEHICLE_CATEGORIES.map((c) => (
            <option key={c.value} value={c.value}>
              {t('fields.vehicleCategory.optionLabel', {
                category: t(`categories.${c.labelKey}`),
                fee: formatCurrency(c.fee, 'EUR'),
              })}
            </option>
          ))}
        </select>
      </label>

      <label className="field">
        <span className="field-label">{t('fields.vin.label')}</span>
        <input
          className="field-input"
          value={vin}
          onChange={(e) => setVin(e.target.value.toUpperCase())}
          placeholder={t('fields.vin.placeholder')}
          disabled={readOnly}
        />
        <span className="field-hint muted">{t('fields.vin.hint')}</span>
      </label>

      <label className="field">
        <span className="field-label">{t('fields.plateNumber.label')}</span>
        <select
          className="field-input"
          value={plateOption}
          onChange={(e) => setPlateOption(e.target.value)}
          disabled={readOnly}
        >
          <option value="random">{t('plateOptions.random')}</option>
          <option value="reserved">{t('plateOptions.reserved')}</option>
        </select>
      </label>

      {plateOption === 'reserved' && (
        <label className="field">
          <span className="field-label">{t('fields.reservedPlateNumber.label')}</span>
          <input
            className="field-input"
            value={reservedPlateNumber}
            onChange={(e) => setReservedPlateNumber(e.target.value)}
            disabled={readOnly}
          />
        </label>
      )}

      {error && <p className="form-error">{t(error)}</p>}

      {!readOnly && (
        <div className="form-actions">
          <button type="submit" className="btn btn-primary" disabled={submitting}>
            {submitting ? t('common:feedback.submitting') : t('actions.submitApplication')}
          </button>
        </div>
      )}
    </form>
  );
}
