import { useState, type FormEvent } from 'react';
import { useTranslation } from 'react-i18next';
import {
  Alert,
  Button,
  Checkbox,
  NumberField,
  Select,
  TextField,
  type ISelectOption,
  type TSelectValue,
} from '@tedi-design-system/react/tedi';
import type { FormProps } from '../types';
import { formatCurrency } from '../../i18n/format';

/**
 * Applicant form for transportLearningPermit (PartA) — ITS Demo Scenario 2.
 * Flat 6 EUR service fee shown before any field is filled (demo
 * requirement: cost visible at the beginning). The eye test is NOT a form
 * field — it is fetched from the approved-opticians registry by civil
 * number after submission.
 *
 * First form built on TEDI (@tedi-design-system/react) instead of the
 * hand-rolled .field/.field-input markup — the reference for converting the
 * remaining forms. TEDI supplies label/hint/error wiring and WCAG 2.2 AA
 * behaviour; validation logic and the CIB seven typed-variable payload are
 * unchanged.
 *
 * Generated by .claude/skills/service-builder from
 * docs/business/services/transport-learning-permit/forms/transport-permit-application.md
 */

const RESIDENCY_OPTIONS = [
  { value: 'citizen', labelKey: 'fields.residencyStatus.options.citizen' },
  { value: 'gcc-citizen', labelKey: 'fields.residencyStatus.options.gccCitizen' },
  { value: 'resident', labelKey: 'fields.residencyStatus.options.resident' },
];

const LICENSE_CATEGORIES = [
  { value: 'light-vehicle', labelKey: 'fields.licenseCategory.options.lightVehicle' },
  { value: 'motorcycle', labelKey: 'fields.licenseCategory.options.motorcycle' },
  { value: 'heavy-vehicle', labelKey: 'fields.licenseCategory.options.heavyVehicle' },
  { value: 'mechanical-equipment', labelKey: 'fields.licenseCategory.options.mechanicalEquipment' },
];

/**
 * TEDI's Select onChange payload is typed for multi-select too; these forms
 * are single-select only, so unwrap to the option's string value.
 */
function singleValue(v: TSelectValue): string | null {
  const opt = Array.isArray(v) ? v[0] : v;
  return opt ? (opt as ISelectOption).value : null;
}

export default function TransportPermitApplicationForm({
  data,
  onComplete,
  submitting,
  readOnly,
}: FormProps) {
  const { t } = useTranslation('transport-permit-application');
  const [applicantName, setApplicantName] = useState((data.applicantName as string) ?? '');
  const [applicantEmail, setApplicantEmail] = useState((data.applicantEmail as string) ?? '');
  const [civilId, setCivilId] = useState((data.civilId as string) ?? '');
  const [age, setAge] = useState<number | undefined>(
    data.age != null ? Number(data.age) : undefined,
  );
  const [residencyStatus, setResidencyStatus] = useState(
    (data.residencyStatus as string) ?? 'citizen',
  );
  const [hasResidentCard, setHasResidentCard] = useState(Boolean(data.hasResidentCard));
  const [licenseCategory, setLicenseCategory] = useState(
    (data.licenseCategory as string) ?? 'light-vehicle',
  );
  const [specialNeeds, setSpecialNeeds] = useState(Boolean(data.specialNeeds));
  const [profession, setProfession] = useState((data.profession as string) ?? '');

  /** i18n key of the current validation error, translated at render time. */
  const [error, setError] = useState<string | null>(null);

  const residencyOptions: ISelectOption[] = RESIDENCY_OPTIONS.map((o) => ({
    value: o.value,
    label: t(o.labelKey),
  }));
  const licenseOptions: ISelectOption[] = LICENSE_CATEGORIES.map((o) => ({
    value: o.value,
    label: t(o.labelKey),
  }));

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError(null);

    if (!applicantName.trim()) {
      setError('errors.nameRequired');
      return;
    }
    if (!applicantEmail.trim() || !applicantEmail.includes('@')) {
      setError('errors.emailInvalid');
      return;
    }
    if (!/^[0-9]{8}$/.test(civilId.trim())) {
      setError('errors.civilIdFormat');
      return;
    }
    if (age == null || !Number.isInteger(age) || age < 15 || age > 100) {
      setError('errors.ageRange');
      return;
    }

    await onComplete({
      applicantName: { value: applicantName.trim(), type: 'String' },
      applicantEmail: { value: applicantEmail.trim(), type: 'String' },
      civilId: { value: civilId.trim(), type: 'String' },
      age: { value: age, type: 'Integer' },
      residencyStatus: { value: residencyStatus, type: 'String' },
      hasResidentCard: { value: hasResidentCard, type: 'Boolean' },
      licenseCategory: { value: licenseCategory, type: 'String' },
      specialNeeds: { value: specialNeeds, type: 'Boolean' },
      profession: { value: profession.trim(), type: 'String' },
    });
  }

  return (
    <form className="form form-tedi" onSubmit={handleSubmit}>
      <p className="form-intro">{readOnly ? t('intro.readOnly') : t('intro.edit')}</p>

      <Alert type="info" title={t('fee.title', { fee: formatCurrency(6, 'EUR') })} role="none">
        {t('fee.body')}
      </Alert>

      <TextField
        id="tpa-applicant-name"
        label={t('fields.applicantName.label')}
        value={applicantName}
        onChange={setApplicantName}
        disabled
        helper={{ text: t('common:identity.fromAccount') }}
      />

      <TextField
        id="tpa-applicant-email"
        label={t('fields.applicantEmail.label')}
        value={applicantEmail}
        onChange={setApplicantEmail}
        disabled
        helper={{ text: t('common:identity.fromAccount') }}
      />

      <TextField
        id="tpa-civil-id"
        label={t('fields.civilId.label')}
        value={civilId}
        onChange={setCivilId}
        placeholder={t('fields.civilId.placeholder')}
        disabled={readOnly}
        helper={{ text: t('fields.civilId.hint') }}
      />

      <NumberField
        id="tpa-age"
        label={t('fields.age.label')}
        value={age}
        onChange={setAge}
        min={15}
        max={100}
        disabled={readOnly}
      />

      <Select
        id="tpa-residency-status"
        label={t('fields.residencyStatus.label')}
        options={residencyOptions}
        value={residencyOptions.find((o) => o.value === residencyStatus)}
        onChange={(v) => {
          const value = singleValue(v);
          if (value) setResidencyStatus(value);
        }}
        isSearchable={false}
        disabled={readOnly}
      />

      <Checkbox
        id="tpa-has-resident-card"
        name="hasResidentCard"
        value="hasResidentCard"
        label={t('fields.hasResidentCard.label')}
        checked={hasResidentCard}
        onChange={(_, checked) => setHasResidentCard(checked)}
        disabled={readOnly}
        helper={{ text: t('fields.hasResidentCard.hint') }}
      />

      <Select
        id="tpa-license-category"
        label={t('fields.licenseCategory.label')}
        options={licenseOptions}
        value={licenseOptions.find((o) => o.value === licenseCategory)}
        onChange={(v) => {
          const value = singleValue(v);
          if (value) setLicenseCategory(value);
        }}
        isSearchable={false}
        disabled={readOnly}
        helper={{ text: t('fields.licenseCategory.hint') }}
      />

      <Checkbox
        id="tpa-special-needs"
        name="specialNeeds"
        value="specialNeeds"
        label={t('fields.specialNeeds.label')}
        checked={specialNeeds}
        onChange={(_, checked) => setSpecialNeeds(checked)}
        disabled={readOnly}
      />

      <TextField
        id="tpa-profession"
        label={t('fields.profession.label')}
        value={profession}
        onChange={setProfession}
        disabled={readOnly}
        helper={{ text: t('fields.profession.hint') }}
      />

      {error && (
        <Alert type="danger" role="alert">
          {t(error)}
        </Alert>
      )}

      {!readOnly && (
        <div className="form-actions">
          <Button type="submit" disabled={submitting}>
            {submitting ? t('common:feedback.submitting') : t('actions.submitApplication')}
          </Button>
        </div>
      )}
    </form>
  );
}
