import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import type { FormProps } from '../types';
import { formatNumber } from '../../i18n/format';

/**
 * Police Hospital medical assessment form for ropLearningPermit (PartB) —
 * ROP ITS Demo Scenario 2. The civil-servant group plays the hospital
 * medical board: the applicant was flagged for weak vision by the
 * approved optician; record whether they are fit to drive. On a negative
 * result the form composes rejectionReason from the notes so the shared
 * rejection-email template renders the hospital's wording.
 *
 * Generated by .claude/skills/service-builder from
 * docs/business/services/rop-learning-permit/forms/rop-hospital-assessment.md
 */
export default function RopHospitalAssessmentForm({
  data,
  onComplete,
  submitting,
  readOnly,
}: FormProps) {
  const { t } = useTranslation('rop-hospital-assessment');
  const [medicalResult, setMedicalResult] = useState<string>('');
  const [medicalNotes, setMedicalNotes] = useState('');
  const [error, setError] = useState<string | null>(null);

  function submitAssessment() {
    setError(null);
    if (medicalResult !== 'positive' && medicalResult !== 'negative') {
      setError('errors.selectResult');
      return;
    }
    const trimmedNotes = medicalNotes.trim();
    if (medicalResult === 'negative' && !trimmedNotes) {
      setError('errors.notesRequired');
      return;
    }
    return onComplete({
      medicalResult: { value: medicalResult, type: 'String' },
      medicalNotes: { value: trimmedNotes, type: 'String' },
      rejectionReason: {
        value:
          medicalResult === 'negative' ? `Police Hospital medical assessment: ${trimmedNotes}` : '',
        type: 'String',
      },
    });
  }

  const recordedResult = (data.medicalResult as string) ?? null;

  return (
    <div className="form">
      <p className="form-intro">{readOnly ? t('intro.readOnly') : t('intro.edit')}</p>

      <dl className="summary">
        <div className="summary-row">
          <dt>{t('summary.applicant')}</dt>
          <dd>{(data.applicantName as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>{t('summary.civilNumber')}</dt>
          <dd>{(data.civilId as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>{t('summary.age')}</dt>
          <dd>{data.age != null ? formatNumber(Number(data.age)) : '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>{t('summary.licenseCategory')}</dt>
          <dd>{(data.licenseCategory as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>{t('summary.specialNeeds')}</dt>
          <dd>
            {data.specialNeeds === true || data.specialNeeds === 'true'
              ? t('summary.yes')
              : t('summary.no')}
          </dd>
        </div>
        <div className="summary-row">
          <dt>{t('summary.eyeTestResult')}</dt>
          <dd className="decision-reject">{t('summary.weakVision')}</dd>
        </div>
        {readOnly && recordedResult && (
          <div className="summary-row">
            <dt>{t('summary.assessment')}</dt>
            <dd className={recordedResult === 'positive' ? 'decision-approve' : 'decision-reject'}>
              {recordedResult === 'positive' ? t('values.fitToDrive') : t('values.notFitToDrive')}
            </dd>
          </div>
        )}
        {readOnly && Boolean(data.medicalNotes as string) && (
          <div className="summary-row">
            <dt>{t('summary.notes')}</dt>
            <dd>{data.medicalNotes as string}</dd>
          </div>
        )}
      </dl>

      {!readOnly && (
        <>
          <div className="field">
            <span className="field-label">{t('fields.medicalResult.label')}</span>
            <label className="field-checkbox">
              <input
                type="radio"
                name="medicalResult"
                value="positive"
                checked={medicalResult === 'positive'}
                onChange={() => setMedicalResult('positive')}
              />
              <span>{t('fields.medicalResult.positive')}</span>
            </label>
            <label className="field-checkbox">
              <input
                type="radio"
                name="medicalResult"
                value="negative"
                checked={medicalResult === 'negative'}
                onChange={() => setMedicalResult('negative')}
              />
              <span>{t('fields.medicalResult.negative')}</span>
            </label>
          </div>

          <label className="field">
            <span className="field-label">{t('fields.medicalNotes.label')}</span>
            <textarea
              className="field-input"
              rows={3}
              value={medicalNotes}
              onChange={(e) => setMedicalNotes(e.target.value)}
              placeholder={
                medicalResult === 'negative'
                  ? t('fields.medicalNotes.placeholderNegative')
                  : t('fields.medicalNotes.placeholderPositive')
              }
            />
          </label>
        </>
      )}

      {error && <p className="form-error">{t(error)}</p>}

      {!readOnly && (
        <div className="form-actions">
          <button className="btn btn-primary" disabled={submitting} onClick={submitAssessment}>
            {submitting ? t('common:feedback.submitting') : t('actions.submitAssessment')}
          </button>
        </div>
      )}
    </div>
  );
}
