import { useState } from 'react';
import type { FormProps } from '../types';

/**
 * Police Hospital medical assessment form for ropLearningPermit (PartB) —
 * ROP ITS Demo Scenario 2. The civil-servant group plays the hospital
 * medical board: the applicant was flagged for weak vision by the
 * approved optician; record whether they are fit to drive. On a negative
 * result the form composes rejectionReason from the notes so the shared
 * rejection-email template renders the hospital's wording.
 *
 * Generated by .claude/skills/service-builder from
 * docs/business/services/rop-learning-permit/forms/rop-hospital-assessment.md
 */
export default function RopHospitalAssessmentForm({
  data,
  onComplete,
  submitting,
  readOnly,
}: FormProps) {
  const [medicalResult, setMedicalResult] = useState<string>('');
  const [medicalNotes, setMedicalNotes] = useState('');
  const [error, setError] = useState<string | null>(null);

  function submitAssessment() {
    setError(null);
    if (medicalResult !== 'positive' && medicalResult !== 'negative') {
      setError('Please select an assessment result.');
      return;
    }
    const trimmedNotes = medicalNotes.trim();
    if (medicalResult === 'negative' && !trimmedNotes) {
      setError('Please add assessment notes — they are sent to the applicant as the reason.');
      return;
    }
    return onComplete({
      medicalResult: { value: medicalResult, type: 'String' },
      medicalNotes: { value: trimmedNotes, type: 'String' },
      rejectionReason: {
        value:
          medicalResult === 'negative'
            ? `Police Hospital medical assessment: ${trimmedNotes}`
            : '',
        type: 'String',
      },
    });
  }

  const recordedResult = (data.medicalResult as string) ?? null;

  return (
    <div className="form">
      <p className="form-intro">
        {readOnly
          ? 'A read-only view of the Police Hospital medical assessment.'
          : 'The approved optician reported weak vision for this applicant. Record the Police Hospital’s medical assessment of their eligibility for a driving license.'}
      </p>

      <dl className="summary">
        <div className="summary-row">
          <dt>Applicant</dt>
          <dd>{(data.applicantName as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>Civil number</dt>
          <dd>{(data.civilId as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>Age</dt>
          <dd>{data.age != null ? String(data.age) : '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>License category</dt>
          <dd>{(data.licenseCategory as string) ?? '—'}</dd>
        </div>
        <div className="summary-row">
          <dt>Special needs</dt>
          <dd>{data.specialNeeds === true || data.specialNeeds === 'true' ? 'yes' : 'no'}</dd>
        </div>
        <div className="summary-row">
          <dt>Eye test result</dt>
          <dd className="decision-reject">weak vision</dd>
        </div>
        {readOnly && recordedResult && (
          <div className="summary-row">
            <dt>Assessment</dt>
            <dd className={recordedResult === 'positive' ? 'decision-approve' : 'decision-reject'}>
              {recordedResult === 'positive' ? 'Fit to drive' : 'Not fit to drive'}
            </dd>
          </div>
        )}
        {readOnly && Boolean(data.medicalNotes as string) && (
          <div className="summary-row">
            <dt>Notes</dt>
            <dd>{data.medicalNotes as string}</dd>
          </div>
        )}
      </dl>

      {!readOnly && (
        <>
          <div className="field">
            <span className="field-label">Assessment result</span>
            <label className="field-checkbox">
              <input
                type="radio"
                name="medicalResult"
                value="positive"
                checked={medicalResult === 'positive'}
                onChange={() => setMedicalResult('positive')}
              />
              <span>Fit to drive — proceed to fee payment</span>
            </label>
            <label className="field-checkbox">
              <input
                type="radio"
                name="medicalResult"
                value="negative"
                checked={medicalResult === 'negative'}
                onChange={() => setMedicalResult('negative')}
              />
              <span>Not fit to drive — reject the application</span>
            </label>
          </div>

          <label className="field">
            <span className="field-label">Assessment notes</span>
            <textarea
              className="field-input"
              rows={3}
              value={medicalNotes}
              onChange={(e) => setMedicalNotes(e.target.value)}
              placeholder={
                medicalResult === 'negative'
                  ? 'Required — sent to the applicant as the rejection reason.'
                  : 'Optional for a positive result.'
              }
            />
          </label>
        </>
      )}

      {error && <p className="form-error">{error}</p>}

      {!readOnly && (
        <div className="form-actions">
          <button className="btn btn-primary" disabled={submitting} onClick={submitAssessment}>
            {submitting ? 'Working…' : 'Submit assessment'}
          </button>
        </div>
      )}
    </div>
  );
}
